apiVersion: v2
name: first-echo
description: Wrapper chart for the first podinfo API instance
type: application
version: 1.0.0
appVersion: "6.7.0"
dependencies:
  - name: podinfo
    version: 6.7.0
    repository: https://stefanprodan.github.io/podinfo
