apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: second-echo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/talawson05/argo-workspace.git'
    targetRevision: HEAD
    path: app-helms/second-echo
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
